services:
  validator:
    image: apps4everything/kosit-validator-xrechnung:3.0.2-1
    container_name: rechnungsmonster-validator

  backend:
    build: ./backend
    container_name: rechnungsmonster-backend
    ports:
      - "8020:8000"
    environment:
      - VALIDATOR_URL=http://validator:8081
    depends_on:
      - validator

  frontend:
    build: ./frontend
    container_name: rechnungsmonster-frontend
    ports:
      - "5175:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
    depends_on:
      - backend
